### ISSUE TITLE
Bug: react content loader displays inconsistent amount of mock cards

### ISSUE THREAD

**Issue by alexbotello** [Lambda-School-Labs/LabsPT1_Backwoods#124]
The amount of loading trip cards displayed is not consistent with the actual amount of trip cards a user has.

For example, I have one trip saved in my list, but react content loader displays 6 mock trip cards.

**Comment by frankfaustino** [comment]
There's no way to know how many placeholders to render ahead of time with the way the data is being fetched currently.

Usman suggested to just render a screen's worth of placeholders, which is the same behavior you see on LinkedIn, YouTube or Facebook:

<img width="1552" alt="screen shot 2019-01-29 at 11 39 01 pm" src="https://user-images.githubusercontent.com/2607929/52095305-59d55580-2577-11e9-8d98-ab47c0ab3f5d.png">
<img width="1552" alt="screen shot 2019-01-29 at 11 37 47 pm" src="https://user-images.githubusercontent.com/2607929/52095306-5a6dec00-2577-11e9-9b4b-4f4ea7e02bf8.png">

If you can think of a way to fetch the number of trips being rendered before fetching the trips themselves, please make a PR!

**Comment by alexbotello** [comment]
Could we not just render the length of the trips state?

```javascript
 renderPlaceholders = () =>
    [...Array(props.trips.length)].map((_, i) => (
      <TripCard archived={false} key={i} loading={true} />
    ))
```

**Comment by frankfaustino** [comment]
Let me try, but wouldn't it be empty since no trips have been fetched yet?

**Comment by frankfaustino** [comment]
Lol yea. The trip model and the way the trips are being fetched could be improved upon. There's a lot of unnecessary code in the frontend that manipulates data to suit its needs.

E.g.:

```js
        lat: waypoint.lat,
        lng: waypoint.lon
```

and

```js
export const getTripsArray = state =>
  Object.keys(state.trips.trips).map(key => state.trips.trips[key])
```
