### ISSUE TITLE
Bug: Pending state not set back to false on registration failure

### ISSUE THREAD

**Issue by ahrjarrett** [Lambda-School-Labs/LabsPT1_Backwoods#76]
State bug where pending remains true when the `REGISTRATION_FAILURE` fires. Causes an infinite hanging loader animation even between route changes.

**Comment by frankfaustino** [comment]
![signup_bug](https://user-images.githubusercontent.com/2607929/51365218-12899800-1a94-11e9-96b0-4780f1b59273.gif)
