### ISSUE TITLE
Feature request: Upgrade to premium screen

### ISSUE THREAD

**Issue by frankfaustino** [Lambda-School-Labs/LabsPT1_Backwoods#83]
Currently our upgrade to premium screen is pretty sparse. We have to give users a reason to upgrade to our premium services:

<img width="1437" alt="screen shot 2019-01-17 at 9 32 56 pm" src="https://user-images.githubusercontent.com/2607929/51367562-102d3b00-1aa0-11e9-8e37-7c16e5fc9051.png">

### Examples

<img width="1324" alt="screen shot 2019-01-17 at 9 35 57 pm" src="https://user-images.githubusercontent.com/2607929/51367576-1c18fd00-1aa0-11e9-9306-bc5d57c52c9e.png">
<img width="1218" alt="screen shot 2019-01-17 at 9 35 10 pm" src="https://user-images.githubusercontent.com/2607929/51367579-1e7b5700-1aa0-11e9-99f9-67c5f333f7db.png">
<img width="1207" alt="screen shot 2019-01-17 at 9 32 35 pm" src="https://user-images.githubusercontent.com/2607929/51367587-24713800-1aa0-11e9-9970-da8638af8fe4.png">
<img width="616" alt="screen shot 2019-01-17 at 9 32 18 pm" src="https://user-images.githubusercontent.com/2607929/51367588-24713800-1aa0-11e9-8cd8-790ca2450180.png">

**Comment by ahrjarrett** [comment]
Love it. Personally I feel like the Airtable option makes the most sense given that we don't have multiple packages, plus it looks clean af
