### ISSUE TITLE
Bug/Tech Debt: Always populate array of trip objects on user fetch

### ISSUE THREAD

**Issue by ahrjarrett** [Lambda-School-Labs/LabsPT1_Backwoods#84]
PropTypes already working its magic. Today it started complaining, it looks like sometimes when we pass a user on props, we're passing a user with an array of trip ids on the `trips` key, and sometimes we're passing an array of trip objects.

At first I thought this boiled down to inconsistent state management on my part, but @alexbotello thinks it might be that what our endpoints aren't always returning the same thing when we ask for a user.

**Comment by alexbotello** [comment]
So GET `/api/user/:id` will always return with the trips property populated (if the user has trips). If we are getting a user with their trips not populated, then that must mean we are not being consistent with our api call. 

Maybe this is a left over thing from when we were grabbing with `user_by_token`. Either way we should make sure that if a trip is modified, deleted, etc. Its corresponding user should reflect those changes in the store.

**Comment by alexbotello** [comment]
@ahrjarrett I think I might know where this is coming from. It looks like when a user first logs in is when the `trips` key is saved to the store as an array of ObjectIds. I checked in the server code and found this in `modules/auth.js`:
```javascript
export const login = (req, res) => {
  const { username, password } = req.body
  User.findOne({ username: username })
    .then(user => {
      if (!user) return res.status(404).send("User does not exist")
      user.comparePassword(password, (err, isMatch) => {
        if (err) {
          return res.status(401).send("Unauthorized")
        }
        if (isMatch) {
          // let token = generateToken(user)
          const token = jwt.sign({ id: user._id }, JWT_SECRET, {
            expiresIn: 86400 // 24 hours
          })

          const payload = { user, token }
          res.status(200).json(payload)
        } else {
          return res.status(401).send("Invalid password")
        }
      })
    })
    .catch(err => {
      res.status(500).send(err)
    })
}
```
This is an oversight on my part, I forgot to come back here and add a `.populate()` cal after all the models were finished.
