### ISSUE TITLE
Bug: StripeProvider component creates new iframe elements in the DOM that is not removed when the component is unmounted

### ISSUE THREAD

**Issue by frankfaustino** [Lambda-School-Labs/LabsPT1_Backwoods#85]
StripeProvider component creates new iframe elements in the DOM that is not removed when the component is unmounted. This occurs when you navigate away from the Billing component and back.

I have a fix in the works.

![screen shot 2019-01-17 at 11 20 44 pm](https://user-images.githubusercontent.com/2607929/51371411-f21b0700-1aae-11e9-9cf7-c66b691ad07a.png)
![screen shot 2019-01-17 at 11 11 56 pm](https://user-images.githubusercontent.com/2607929/51371414-f47d6100-1aae-11e9-918d-824cb20cc102.png)

**Comment by ahrjarrett** [comment]
Is this a matter of making a call in componentWillUnmount?

This could be related to the fact that I moved the Stripe config out of a script tag in index.html and put it in the component, worst case scenario we could go back to that.

Also if I remember correctly Stripe mounts inside a `setTimeout` callback to make sure it's ready, this could be handled more responsibly IMO.

@iamthuypham

**Comment by frankfaustino** [comment]
I tried removing the `script` tag, the `iframe` and `window.Stripe` object in `componentWillUnmount` and what ends up happening is upon visiting the Billing page again, the `iframe` get generated again but now TWO TIMES with a different `_id`s.

I'll have to take another approach.
